<a href="https://colab.research.google.com/github/abnv16/learn_py/blob/main/Copy_of_Copy_of_TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
import numpy as np
import random
 
 
matrix = np.random.randint(100, size=(3, 3))
print(matrix)

[[79 47 67]
 [27 28 47]
 [ 5 85 81]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [3]:
import numpy as np
import random
 
array = np.random.randint(100, size=(4, 4))
print("4x4 matrix : ",array)
newarr=array.reshape(2,8)
print("2x8 matrix : ",newarr)
ho=np.hstack(newarr)
ve=np.vstack(newarr)
 
print("horizontal stack :",ho)
print("vertical stack :",ve)

4x4 matrix :  [[60 15 95  4]
 [54 84 77 83]
 [54 67 46 48]
 [11  9 49 49]]
2x8 matrix :  [[60 15 95  4 54 84 77 83]
 [54 67 46 48 11  9 49 49]]
horizontal stack : [60 15 95  4 54 84 77 83 54 67 46 48 11  9 49 49]
vertical stack : [[60 15 95  4 54 84 77 83]
 [54 67 46 48 11  9 49 49]]
