<a href="https://colab.research.google.com/github/abnv16/learn_py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
import numpy as np
import random

sample=[random.randrange(1,100)for i in range (9)]
arr=np.array(sample)
newarr=arr.reshape(3,3)
print(newarr)


[[43 84  6]
 [98 78 14]
 [17 86 13]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
import numpy as np
import random

sample=[random.randrange(1,100)for i in range (16)]
arr=np.array(sample)
newarr=arr.reshape(4,4)
print("4x4 matrix : ",newarr)
newarr1=newarr.reshape(2,8)
print("2x8 matrix : ",newarr1)
ho=np.hstack(newarr1)
ve=np.vstack(newarr1)

print("horizontal stack :",ho)
print("vertical stack :",ve)


4x4 matrix :  [[12 54 28 40]
 [57 25 62 41]
 [79 77 63  5]
 [36 88 86 49]]
2x8 matrix :  [[12 54 28 40 57 25 62 41]
 [79 77 63  5 36 88 86 49]]
horizontal stack : [12 54 28 40 57 25 62 41 79 77 63  5 36 88 86 49]
vertical stack : [[12 54 28 40 57 25 62 41]
 [79 77 63  5 36 88 86 49]]
