<a href="https://colab.research.google.com/github/abnv16/learn_py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [ ]:
 import numpy as np
 
array=np.arange(0,9)
arr1=array.reshape(3,3)
print ("array 1: ",arr1)
 
array2=np.arange(10,19)
arr2=array2.reshape(3,3)
print ("array 2 :",arr2)
 
out=np.outer(arr1,arr2)
print("Outer product:\n",out)
 
dot=np.dot(arr1,arr2)
print("dot product : \n",dot)
 
multi=np.multiply(arr1,arr2)
print("element wise product :\n",multi)

array 1:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
array 2 : [[10 11 12]
 [13 14 15]
 [16 17 18]]
Outer product:
 [[  0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18]
 [ 20  22  24  26  28  30  32  34  36]
 [ 30  33  36  39  42  45  48  51  54]
 [ 40  44  48  52  56  60  64  68  72]
 [ 50  55  60  65  70  75  80  85  90]
 [ 60  66  72  78  84  90  96 102 108]
 [ 70  77  84  91  98 105 112 119 126]
 [ 80  88  96 104 112 120 128 136 144]]
dot product : 
 [[ 45  48  51]
 [162 174 186]
 [279 300 321]]
element wise product :
 [[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [18]:
import numpy as np
 
arr=np.arange (0,16)
arr1=arr.reshape(4,4)
print(arr1)
 
ad=arr1+4
print("add :\n",ad)
 
arr2=[1,2,3,4]
multi=arr1*arr2
print ("multiplication : \n",multi)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
add :
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
multiplication : 
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]]
