<a href="https://colab.research.google.com/github/abnv16/learn_py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [4]:
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-08-31',periods=4) 
df = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD')) 
print("Head:\n", df.head(n=2)) 
print("Tail:\n", df.tail(n=2)) 
print("Index:\n", df.index) 
print("Columns:\n", df.columns) 
print("Values:\n", df.values) 
print("Statistics:\n", df.describe(include='all'))

Head:
                    A         B         C         D
2021-08-31  0.554636 -0.458144 -0.506081 -1.140856
2021-09-01  0.881138 -0.059952  1.617083 -0.651229
Tail:
                    A         B        C         D
2021-09-02 -0.960523 -0.299863  1.31227  0.174914
2021-09-03  0.232456  1.313706  0.40954 -0.086865
Index:
 DatetimeIndex(['2021-08-31', '2021-09-01', '2021-09-02', '2021-09-03'], dtype='datetime64[ns]', freq='D')
Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[ 0.55463566 -0.45814438 -0.50608142 -1.14085603]
 [ 0.88113819 -0.05995234  1.61708347 -0.65122884]
 [-0.96052312 -0.29986344  1.3122702   0.17491415]
 [ 0.23245557  1.31370648  0.40954001 -0.08686484]]
Statistics:
               A         B         C         D
count  4.000000  4.000000  4.000000  4.000000
mean   0.176927  0.123937  0.708203 -0.426009
std    0.803213  0.809896  0.958236  0.588177
min   -0.960523 -0.458144 -0.506081 -1.140856
25%   -0.065789 -0.339434  0.180635 -0.773636
50%    0.393

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [ ]:
print("Transpose\n", df.transpose()) 
print("Sorted in Descending Order\n", df.sort_index(ascending=False))

Transpose
    2021-08-24  2021-08-25  2021-08-26  2021-08-27
A    0.181591    0.568585   -0.164965    0.976366
B    2.359344    0.172435    0.736717    0.220670
C   -0.728234    0.411873   -0.229653   -0.641891
D    0.892118    0.700101    0.108273    1.277697
Sorted in Descending Order
                    A         B         C         D
2021-08-27  0.976366  0.220670 -0.641891  1.277697
2021-08-26 -0.164965  0.736717 -0.229653  0.108273
2021-08-25  0.568585  0.172435  0.411873  0.700101
2021-08-24  0.181591  2.359344 -0.728234  0.892118
