<a href="https://colab.research.google.com/github/abnv16/learn_py/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [ ]:
import numpy as np
import random
 
array=np.arange(0,16)
arr2=array.reshape(4,4)
print (arr2)
 
arrh=np.hsplit(arr2,2)
print ("horizontal split" ,arrh)
 
arrv=np.vsplit (arr2,4)
print ("vertical split",arrv)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
horizontal split [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
vertical split [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [ ]:
 
import numpy as np
import random
 
 
arr = np.random.rand(3, 3)
print("3x3 matrix", arr)
arr2=np.ceil(arr)
print ("ceil",arr2)
 
arr3=np.floor(arr)
print ("floor",arr3)

3x3 matrix [[0.69774455 0.37658753 0.87660254]
 [0.12671707 0.89531728 0.13104597]
 [0.13752763 0.20479914 0.53117606]]
ceil [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
floor [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [ ]:
 
 matrix = np.random.randint(10, size=(1, 4))
print ("matrix =\n",matrix)
print("shape =",matrix.shape)
 
a=matrix.squeeze()
print("squeezed array",a)
print("squeezed array shape",a.shape)
exp=np.expand_dims(matrix,axis=1)
print("shape :\n",exp.shape)

matrix =
 [[7 1 1 3]]
shape = (1, 4)
squeezed array [7 1 1 3]
squeezed array shape (4,)
shape :
 (1, 1, 4)
